export const SET_RASTER = "SET_RASTER";

export const CHANGE_TOOL = "CHANGE_TOOL";
export const TOOL_EDIT_AN_OUTLINE = "TOOL_EDIT_AN_OUTLINE";
export const TOOL_EDIT_TESSELATIONS = "TOOL_EDIT_TESSELATIONS";
