export const CHANGE_TOOL = "CHANGE_TOOL";
export const TOOL_IMPORT_RASTER = "TOOL_IMPORT_RASTER";
export const TOOL_EDIT_AN_OUTLINE = "TOOL_EDIT_AN_OUTLINE";
export const TOOL_EDIT_TESSELATIONS = "TOOL_EDIT_TESSELATIONS";
export const TOOL_SAVE_ART = "TOOL_SAVE_ART";
